site_name: My Docs
site_url: https://github.com/orlando-code/cancer-prediction-rt582
repo_url: https://github.com/orlando-code/cancer-prediction-rt582
nav:
  - Home: index.md
  - cancer-prediction:
    - cancer model: cancer-prediction/cancer_model.md
    - streamlit app: cancer-prediction/streamlit_app.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for file changes